version: "2"

services:
  client:
    build:
      context: ./client
      args:
        port: 3001
    image: vanhtuan0409/web-client:${TAG}
    environment:
      NODE_ENV: development
    volumes:
      - ./client/src:/usr/app/src:rw
    ports:
      - "3001:3001"
  
  server:
    build:
      context: ./server
      args:
        port: 8081
    image: vanhtuan0409/web-server:${TAG}
    environment:
      NODE_ENV: development
    ports:
      - "8081:8081"

  gateway:
    build:
      context: ./gateway
    image: vanhtuan0409/gateway:${TAG}
    environment:
      CLIENT_PORT: 3001
      API_PORT: 8081
    ports:
      - "80:80"
    links:
      - server:webapi
      - client:webclient
      