version: "2"

services:
  client:
    build:
      context: ./client
      args:
        port: ${CLIENT_PORT}
    image: vanhtuan0409/web-client:${TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./client/src:/usr/app/src:rw
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
  
  server:
    build:
      context: ./server
      args:
        port: ${API_PORT}
    image: vanhtuan0409/web-server:${TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${API_PORT}:${API_PORT}"

  gateway:
    build:
      context: ./gateway
    image: vanhtuan0409/gateway:${TAG}
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      API_PORT: ${API_PORT}
    ports:
      - "80:80"
    links:
      - server:webapi
      - client:webclient
      